name: 10-minute-cron
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl 'http://216.24.255.71:8080/rent13' 
